spring:
  h2:
    console:
      enabled: 'true'
      path: /h2

  datasource:
    username: Test
    url: jdbc:h2:mem:testdb1
    driverClassName: org.h2.Driver
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: create
